### ISSUE TITLE
Argon2 password verification

### ISSUE THREAD

**Issue by Nukesor** [drriguz/encryptions#10]
Hi :)

First of all, thanks for providing this library.
I just looked through your implementation and API docs, but I couldn't find a method to verify a password with given argon2 hash.

Did I overlook something or is this a feature that's planned to be added later on?
In case I overlooked it, it would be awesome to have an example added to the README of the project :)

Specifically from the `argon2` string format. E.g.:
```
$argon2i$v=19$m=256,t=32,p=2$vyY1x5SY8kA3KiIng2BMkw$/BBUonur9Ph580Ip9Arrf4kfH+TnPJVjPyyaXuSWzxY
```

Thanks in advance!

**Comment by drriguz** [comment]
Hi, that's really a good point, a verify API shoule be provided otherwise the only way to verify the password is to encrypt the password using same parameters(might be hardcoded) again.

I've checked [the original library](https://github.com/P-H-C/phc-winner-argon2/blob/master/include/argon2.h), there is already such verify methods like `argon2i_verify`, it should be easy to integrate with it since the library is just a wrapper for it.

**Comment by Nukesor** [comment]
I actually switched to dargon2, which already implements this feature (even if it's a bit hidden :) )
